"""create teble 'Message'

Revision ID: 65933eef5e81
Revises: 
Create Date: 2023-07-14 21:47:40.263158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65933eef5e81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
