common:
  host: localhost
  port: 8080 # порт, на котором будет запускаться наше приложение
postgres:
  database_url: postgres://username:password@database_host:database_port/database_name
  require_ssl: false # стоит ли шифровать соединение с базой